"""
Generates Kubernetes and CloudFormation manifests as strings,
based on project configuration collected from the UI.
No files need to exist in the user's repo.
The Jenkinsfile will write these to disk via heredoc during the pipeline.
"""


def generate_k8s_deployment(project) -> str:
    """Generate a Kubernetes Deployment manifest."""
    replicas = project.k8s_replicas or 1
    cpu_req  = project.k8s_cpu_request or '100m'
    mem_req  = project.k8s_memory_request or '128Mi'
    cpu_lim  = project.k8s_cpu_limit or '500m'
    mem_lim  = project.k8s_memory_limit or '512Mi'
    image    = project.image_name or f"{project.dockerhub_username}/{project.jenkins_job_name}"
    port     = project.container_port or 8000
    job      = project.jenkins_job_name
    env      = project.environment

    manifest = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {job}
  labels:
    app: {job}
    env: {env}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {job}
  template:
    metadata:
      labels:
        app: {job}
        env: {env}
    spec:
      containers:
        - name: {job}
          image: {image}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {port}
          resources:
            requests:
              cpu: {cpu_req}
              memory: {mem_req}
            limits:
              cpu: {cpu_lim}
              memory: {mem_lim}
"""

    # Add env vars if defined
    if project.k8s_env_vars:
        manifest += "          env:\n"
        for line in project.k8s_env_vars.strip().splitlines():
            line = line.strip()
            if '=' in line:
                key, _, value = line.partition('=')
                manifest += f"            - name: {key.strip()}\n"
                manifest += f"              value: \"{value.strip()}\"\n"

    # Add health check if port is known
    manifest += f"""          readinessProbe:
            tcpSocket:
              port: {port}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {port}
            initialDelaySeconds: 20
            periodSeconds: 10
"""
    return manifest


def generate_k8s_service(project) -> str:
    """Generate a Kubernetes Service manifest (NodePort)."""
    job        = project.jenkins_job_name
    node_port  = project.app_port or 30080
    cont_port  = project.container_port or 8000

    return f"""apiVersion: v1
kind: Service
metadata:
  name: {job}-service
  labels:
    app: {job}
spec:
  type: NodePort
  selector:
    app: {job}
  ports:
    - protocol: TCP
      port: {cont_port}
      targetPort: {cont_port}
      nodePort: {node_port}
"""


def generate_cloudformation(project) -> str:
    """
    Generate a CloudFormation template that provisions:
    - A VPC with a public subnet
    - A security group (SSH + app port)
    - An EC2 instance with k3s pre-installed via UserData
    """
    job         = project.jenkins_job_name
    key_name    = project.aws_key_name or 'vockey'
    app_port    = project.app_port or 30080
    instance_type = project.ec2_instance_type or 't3.small'
    # Amazon Linux 2 AMI (us-east-1) — users can override via parameter
    default_ami = 'ami-0c02fb55956c7d316'

    return f"""AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Infrastructure stack for {job} - VPC, EC2 with k3s, security group.
  Generated by CI/CD Platform.

Parameters:
  ProjectName:
    Type: String
    Default: {job}
    Description: Project / deployment name

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: {key_name}
    Description: EC2 Key Pair for SSH access

  InstanceType:
    Type: String
    Default: {instance_type}
    AllowedValues: [t3.micro, t3.small, t3.medium, t3.large]
    Description: EC2 instance type

  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Amazon Linux 2 AMI (auto-resolved via SSM)

Resources:

  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${{ProjectName}}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${{ProjectName}}-igw"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub "${{ProjectName}}-public-subnet"

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${{ProjectName}} security group"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH
        - IpProtocol: tcp
          FromPort: {app_port}
          ToPort: {app_port}
          CidrIp: 0.0.0.0/0
          Description: Application NodePort
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6443
          CidrIp: 0.0.0.0/0
          Description: k3s API server
      Tags:
        - Key: Name
          Value: !Sub "${{ProjectName}}-sg"

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AmiId
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${{ProjectName}}-server"
        - Key: Project
          Value: !Ref ProjectName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          yum update -y
          # Install k3s
          curl -sfL https://get.k3s.io | sh -
          systemctl enable k3s
          systemctl start k3s
          # Wait for k3s to be ready
          until kubectl get nodes 2>/dev/null | grep -q Ready; do sleep 5; done
          echo "k3s ready"
          # Install AWS CLI v2
          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          /tmp/aws/install
          echo "Setup complete"

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub "${{ProjectName}}-PublicIP"

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref SecurityGroup
"""
