# Generated by Django 6.0.5 on 2026-05-08 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_url', models.URLField(help_text='https://github.com/user/repo.git')),
                ('branch', models.CharField(default='main', max_length=100)),
                ('cloud_provider', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('Azure', 'Microsoft Azure'), ('GCP', 'Google Cloud Platform')], default='AWS', max_length=10)),
                ('environment', models.CharField(choices=[('dev', 'Développement'), ('staging', 'Staging'), ('prod', 'Production')], default='staging', max_length=10)),
                ('aws_region', models.CharField(blank=True, choices=[('us-east-1', 'US East (N. Virginia)'), ('us-west-2', 'US West (Oregon)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-central-1', 'Europe (Frankfurt)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)')], default='us-east-1', max_length=30)),
                ('aws_account_id', models.CharField(blank=True, help_text='12-digit AWS account ID', max_length=20)),
                ('aws_key_name', models.CharField(blank=True, help_text='EC2 Key Pair name (ex: vockey)', max_length=100)),
                ('cf_stack_name', models.CharField(blank=True, help_text='CloudFormation stack name', max_length=100)),
                ('dockerhub_username', models.CharField(blank=True, max_length=100)),
                ('image_name', models.CharField(blank=True, help_text='dockerhub_user/image-name', max_length=200)),
                ('jenkins_job_name', models.CharField(blank=True, max_length=200)),
                ('jenkins_created', models.BooleanField(default=False)),
                ('k8s_deployment_file', models.CharField(default='k8s/deployment.yaml', max_length=200)),
                ('k8s_service_file', models.CharField(default='k8s/service.yaml', max_length=200)),
                ('cf_template_file', models.CharField(default='cloudformation/infra-stack.yaml', max_length=200)),
                ('app_port', models.IntegerField(default=30080, help_text='NodePort exposed by k3s')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
