# Generated by Django 4.2.30 on 2026-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='container_port',
            field=models.IntegerField(default=8000, help_text='Port your app listens on inside the container'),
        ),
        migrations.AddField(
            model_name='project',
            name='ec2_instance_type',
            field=models.CharField(blank=True, choices=[('t3.micro', 't3.micro  (1 vCPU, 1 GB)'), ('t3.small', 't3.small  (2 vCPU, 2 GB)'), ('t3.medium', 't3.medium (2 vCPU, 4 GB)'), ('t3.large', 't3.large  (2 vCPU, 8 GB)')], default='t3.small', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='generate_manifests',
            field=models.BooleanField(default=True, help_text='Auto-generate k8s + CF manifests'),
        ),
        migrations.AddField(
            model_name='project',
            name='k8s_cpu_limit',
            field=models.CharField(blank=True, default='500m', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='k8s_cpu_request',
            field=models.CharField(blank=True, default='100m', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='k8s_env_vars',
            field=models.TextField(blank=True, help_text='KEY=VALUE pairs, one per line'),
        ),
        migrations.AddField(
            model_name='project',
            name='k8s_memory_limit',
            field=models.CharField(blank=True, default='512Mi', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='k8s_memory_request',
            field=models.CharField(blank=True, default='128Mi', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='k8s_replicas',
            field=models.IntegerField(default=1, help_text='Number of pod replicas'),
        ),
    ]
