# Generated by Django 6.0.5 on 2026-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aws_access_key_id',
            field=models.CharField(blank=True, help_text='AWS Access Key ID (ex: ASIAT6RJ6QS2...)', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='aws_secret_access_key',
            field=models.CharField(blank=True, help_text='AWS Secret Access Key', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='aws_session_token',
            field=models.TextField(blank=True, help_text='AWS Session Token (Learner Lab uniquement)'),
        ),
        migrations.AddField(
            model_name='project',
            name='dockerhub_token',
            field=models.CharField(blank=True, help_text='DockerHub Access Token (pas le mot de passe)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='ec2_private_key',
            field=models.TextField(blank=True, help_text='Contenu du fichier .pem (clé privée SSH EC2)'),
        ),
        migrations.AddField(
            model_name='project',
            name='jenkins_creds_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_port',
            field=models.IntegerField(default=30080),
        ),
        migrations.AlterField(
            model_name='project',
            name='aws_account_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='aws_key_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='cf_stack_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
